-- ==========================================================
-- Project: Customer Churn Analysis
-- File: 04_Advanced_SQL.sql
-- Description: Advanced SQL Analysis using CASE, CTEs,
--              Window Functions and Ranking
-- ==========================================================

-- 1. Customer Segmentation by Tenure
-- Business Question:
-- Which tenure group has the highest churn rate?

SELECT
    CASE
        WHEN tenure <= 12 THEN '0-1 Year'
        WHEN tenure <= 24 THEN '1-2 Years'
        WHEN tenure <= 48 THEN '2-4 Years'
        ELSE '4+ Years'
    END AS tenure_group,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY tenure_group
ORDER BY churn_rate DESC;

-- 2. Customer Segmentation by Monthly Charges
-- Business Question:
-- Does churn vary with monthly charges?

SELECT
    CASE
        WHEN MonthlyCharges < 35 THEN 'Low'
        WHEN MonthlyCharges < 70 THEN 'Medium'
        ELSE 'High'
    END AS charge_category,
    COUNT(*) AS customers,
    ROUND(AVG(tenure),2) AS avg_tenure,
    ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY charge_category
ORDER BY churn_rate DESC;

-- 3. Top 10 Highest Paying Customers
-- Business Question:
-- Which customers have generated the most revenue?

SELECT
    customerID,
    TotalCharges
FROM customer_churn
ORDER BY TotalCharges DESC
LIMIT 10;

-- 4. Rank Customers by Total Charges
-- Business Question:
-- Rank customers based on lifetime revenue.

SELECT
    customerID,
    TotalCharges,
    RANK() OVER(ORDER BY TotalCharges DESC) AS revenue_rank
FROM customer_churn;

-- 5. Dense Rank by Monthly Charges
-- Business Question:
-- Rank customers according to monthly charges.

SELECT
    customerID,
    MonthlyCharges,
    DENSE_RANK() OVER(ORDER BY MonthlyCharges DESC) AS monthly_rank
FROM customer_churn;

-- 6. Revenue Contribution by Contract Type
-- Business Question:
-- Which contract contributes the most revenue?

SELECT
    Contract,
    ROUND(SUM(TotalCharges),2) AS revenue_generated
FROM customer_churn
GROUP BY Contract
ORDER BY revenue_generated DESC;

-- 7. Common Table Expression (CTE)
-- Business Question:
-- Which contract types have churn rates above the overall average?

WITH contract_churn AS
(
SELECT
    Contract,
    ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY Contract
)

SELECT *
FROM contract_churn
WHERE churn_rate >
(
SELECT
ROUND(
SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),
2)
FROM customer_churn
);

-- 8. Running Revenue
-- Business Question:
-- Calculate cumulative revenue generated by customers.

SELECT
    customerID,
    TotalCharges,
    SUM(TotalCharges)
    OVER(
        ORDER BY TotalCharges
    ) AS cumulative_revenue
FROM customer_churn;

-- 9. NTILE Segmentation
-- Business Question:
-- Divide customers into four revenue groups.

SELECT
    customerID,
    TotalCharges,
    NTILE(4)
    OVER(
        ORDER BY TotalCharges DESC
    ) AS revenue_quartile
FROM customer_churn;

-- 10. High Risk Customers
-- Business Question:
-- Identify customers who are most likely to churn.

SELECT
    customerID,
    tenure,
    MonthlyCharges,
    Contract,
    PaymentMethod
FROM customer_churn
WHERE
tenure < 12
AND MonthlyCharges > 70
AND Contract='Month-to-month'
ORDER BY MonthlyCharges DESC;